steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA', '.']
    secretEnv: ['DISCORD_BOT_TOKEN', 'DISCORD_WATCHED_CHANNELS']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy $_SERVICE_NAME \
          --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA \
          --region=$_DEPLOY_REGION \
          --platform=managed \
          --quiet \
          --update-env-vars=DISCORD_BOT_TOKEN=$$DISCORD_BOT_TOKEN,DISCORD_WATCHED_CHANNELS=$$DISCORD_WATCHED_CHANNELS
    secretEnv: ['DISCORD_BOT_TOKEN', 'DISCORD_WATCHED_CHANNELS']
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DISCORD_BOT_TOKEN/versions/latest
      env: 'DISCORD_BOT_TOKEN'
    - versionName: projects/$PROJECT_ID/secrets/DISCORD_WATCHED_CHANNELS/versions/latest
      env: 'DISCORD_WATCHED_CHANNELS'
