name: Deploy to Cloud Run

on:
  push:
    branches:
      - main # Cambia esto si usas otra rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Autenticar con Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # 3. Configurar gcloud
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # 4. Construir la imagen de Docker
      - name: Build Docker image
        run: |
          IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-service:latest
          docker build -t $IMAGE_NAME .

      # 5. Autenticar Docker con gcloud
      - name: Authenticate Docker with gcloud
        run: gcloud auth configure-docker

      # 6. Subir la imagen de Docker a Container Registry
      - name: Push Docker image to Container Registry
        run: docker push $IMAGE_NAME

      # 7. Desplegar en Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-new-service \
            --image $IMAGE_NAME \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated
