name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-service:latest
          docker build -t $IMAGE_NAME .

      - name: Authenticate Docker with gcloud
        run: gcloud auth configure-docker

      - name: Push Docker image to Container Registry
        run: docker push $IMAGE_NAME

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-new-service \
            --image $IMAGE_NAME \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated