name: Deploy to Cloud Run (Development)

on:
  push:
    branches:
      - dev

env:
  REPO_NAME: cafeteriadelcaos
  SERVICE_NAME: cafeteria-del-caos-api-dev
  IMAGE_NAME: cafeteria-del-caos-api-dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: Build Docker image
        run: |
          IMAGE_PATH=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest
          docker build -t $IMAGE_PATH .

      - name: Push Docker image to Artifact Registry
        run: docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Cloud Run with Dynamic Environment Variables
        run: |
          ENV_VARS=(
            "DB_HOST=${{ secrets.DEV_DB_HOST }}"
            "DB_PORT=${{ secrets.DEV_DB_PORT }}"
            "DB_USERNAME=${{ secrets.DEV_DB_USERNAME }}"
            "DB_PASSWORD=${{ secrets.DEV_DB_PASSWORD }}"
            "DB_NAME=${{ secrets.DEV_DB_NAME }}"
            "DB_SYNCHRONIZE=${{ secrets.DEV_DB_SYNCHRONIZE }}"
            "FIREBASE_PROJECT_ID=${{ secrets.DEV_FIREBASE_PROJECT_ID }}"
            "FIREBASE_CLIENT_EMAIL=${{ secrets.DEV_FIREBASE_CLIENT_EMAIL }}"
            "FIREBASE_PRIVATE_KEY=${{ secrets.DEV_FIREBASE_PRIVATE_KEY }}"
            "DISCORD_BOT_TOKEN=${{ secrets.DEV_DISCORD_BOT_TOKEN }}"
            "DISCORD_CLIENT_ID=${{ secrets.DEV_DISCORD_CLIENT_ID }}"
            "DISCORD_GUILD_ID=${{ secrets.DEV_DISCORD_GUILD_ID }}"
            "DISCORD_PUBLIC_KEY=${{ secrets.DEV_DISCORD_PUBLIC_KEY }}"
            "FRONT_URL=${{ secrets.DEV_FRONT_URL }}"
            "BOT_SYNC_KEY=${{ secrets.DEV_BOT_SYNC_KEY }}"
          )

          ENV_STRING=$(IFS=,; echo "${ENV_VARS[*]}")

          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --timeout=300 \
            --set-env-vars "$ENV_STRING"